name: "daredb-docs"

services:
    dev:
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
    # nginx:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.nginx
    #     ports:
    #         - "127.0.0.1:3001:3001"
    #     volumes:
    #         - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    #     depends_on:
    #         - dev
