name: Build and Deploy
on: [push]
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18 here
          
      - name: Install dependencies
        run: (cd website && npm install)

      - name: Build site
        run: (cd website && npm run build)          
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/build